### PR TITLE
Added function to toggle user account enabled/disabled

### PR DESCRIPTION
**Pull request by nickzer0**
Adding `--toggle-enabled` flag to enable/disable user accounts.

Great tool, thanks for sharing!

### CODE REVIEW

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,
Thanks you for the PR. Is it possible to update the C# README with the new help menu and an example ?

:sunflower:

**Comment by nickzer0** [comment]
Done, also updated the variable used from "target" to "account" in line with the rest of the functions.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Sorry but can you also update this [section](https://github.com/AlmondOffSec/PassTheCert/tree/main/C%23#usage) of the README with the new help output?

**Comment by the-useless-one** [comment]
Tested and worked, thanks for the contribution!

**Pull request merged**
